matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"

script:
  - brew install php72 tree # remove this line
  - bash ./scripts/install-composer.sh
  - bash ./scripts/zip.sh
  - yarn release
  
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
