matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"

before-script:
  - brew install php72 tree # remove this line
  - bash ./install-composer.sh
  - bash ./zip.sh

script:
  - yarn release
  
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
