version: 2
jobs:
  build-windows-linux:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: add-apt-repository -y ppa:ondrej/php && apt-get update && apt-get install tree php7.2 -y # remove this line
      - run: bash ./scripts/install-composer.sh
      - run: bash ./scripts/zip.sh
      - run: yarn && yarn release --win --linux

workflows:
  version: 2
  build:
    jobs:
      - build-windows-linux
